### ISSUE TITLE
NullReferenceException due to Key being Null in ‎MagicalBox.ReaderCache

### ISSUE THREAD

**Issue by fitdev** [Cysharp/ZLogger#158] opened 2024-04-15 09:17 UTC
When I was debugging the code for issue #157 , I got a lot of NullReferenceExceptions in ‎`MagicalBox` complaining that dictionary's key is `null`, apparently `null`s get passed to Dictionary lookup routines, where a concrete `Type` instance is expected for the key.

Since this library intends to be highly performant, throwing such exceptions is not good, and it would be better to avoid such calls by checking in advance if key is null and simply not performing dictionary lookups.

**Comment by neuecc** [comment] 2024-07-01 10:02
Please give a little more detail.
Are you saying that the key in the `ConcurrentDictionary<Type, Handlers> cache`'s Type key will be null?

**Comment by fitdev** [comment] 2024-07-01 11:29
> Are you saying that the key in the ConcurrentDictionary<Type, Handlers> cache's Type key will be null?
Yes, exactly!

**Comment by neuecc** [comment] 2024-07-01 12:02
What kind of situation would cause Type to be null?

**Comment by fitdev** [comment] 2024-07-01 14:00
Unfortunately I do not now remember exactly. But it had something to do with the other IEnumerable issue and Json Serialization. I think under some circumstances the type could not be determined or did not apply along some path within ZLogger or the methods it would call, and thus ended up being null.

**Comment by neuecc** [comment] 2024-07-01 23:31
The cache only uses TryAdd typeof(T) or TryGet, so it looks like it can't happen.
Unless you are running something different for debugging purposes.

**Comment by fitdev** [comment] 2024-07-02 06:57
I was able to dig up a screenshot from that debugging session:

![Screenshot_20240702_095712](https://github.com/Cysharp/ZLogger/assets/8166847/12075e1a-1362-482a-a975-a320ada9a912)

So it happens not when adding a new item, but when checking the item exists.

**Comment by neuecc** [comment] 2024-07-02 07:09
Thank you.
The Type being passed there is InterpolatedStringParameter.Type, which is generated by passing typeof(T) in the constructor.
Therefore, there should be no case where null comes here.
However, since InterpolatedStringParameter is a struct, if an uninitialized InterpolatedStringParameter is passed, it could become null.
For example, since this is being retrieved from an array `InterpolatedStringParameter[]`, if we're retrieving an uninitialized value from outside the initialized range, we would end up passing null.

Of course, if that were to happen, it would be a critical issue.
And if we were to fix it, we shouldn't modify MagicalBox.ReaderCache, but rather fix the state where null is being passed in the first place.

**Comment by fitdev** [comment] 2024-07-02 08:01
Yes, that makes sense. I still unfortunately do not remember now the exact circumstances now why it happened, but I think it had to do with json and serialization, and the fact that it was serializing IEnumerables as collections (which was wrong for my purposes as they had custom json serialization logic). I wish I could provide more info, but I do not remember the exact circumstances now.

**Comment by neuecc** [comment] 2024-07-23 09:01
Since the reproduction condition is unknown, close this once.

**Closed by neuecc** 2024-07-23 09:01 UTC

**Comment by SGSmithI** [comment] 2025-01-30 15:09
@neuecc Found what I think is a repro for this issue. I was writing an assert method which forwards to ZLogger and found that I was getting a null exception when trying to check `type.IsEnum` in `MagicalBox.TryReadTo`. The issue was that the interpolated string handler wasn't clearing the static `literalPool` when the assert didn't fire. As a result the next time a log was made, the `segments` list in `MessageSequence` would be larger than `literalLength` as `literals` had been appended to more than expected. To resolve this I can call `.InnerHandler.GetState();` to force the list to be cleared. If the interpolated string handler had a Dispose method it might have been clearer that there was some state I needed to clean up.

```
public static void ZAssert(this ILogger logger, bool condition,
    [InterpolatedStringHandlerArgument(new[] { "logger" })]
    ref ZLoggerCriticalInterpolatedStringHandler message, object? context = null,
    [CallerMemberName] string? memberName = null, [CallerFilePath] string? filePath = null,
    [CallerLineNumber] int lineNumber = 0)
{
    if (!condition)
    {
        // Must call GetState to clear out the shared list (`literalPool`)!
        message.InnerHandler.GetState();
        return;
    }
    
    // ...
}
```

**Comment by neuecc** [comment] 2025-03-05 08:30
Thank you, I think that's a good observation.
Having custom code that's difficult to write was a bit of poor design.
However, as long as you're using the standard implementation, it's controlled by IsLoggerEnabled, and when literals are being used, GetState is always called.
So I don't think this is directly connected to the root cause.
